---
title: "A Market-Process Approach to the Economic Problem"
author:
- affiliation: FIN 5350
  name: Jared Black
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    df_print: paged
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    keep_tex: yes
    latex_engine: pdflatex
    template: ./svm-latex-ms.tex
biblio-style: apsr
fontfamily: mathpazo
fontsize: 11pt
geometry: margin=1in
keywords: 'Bayesian statistics, DSGE '
bibliography: ./master.bib
spacing: double
abstract: This article explores the purpose of economic models and suggests that economists
  should use Bayesian methods to build models that more accurately reflect the real
  world. The purpose of building models is to solve problems in markets and prevent
  catastrophic financial crises.
---


>  

# Introduction

  The role of economists should be to prevent, or to at least lessen, the disastrous effects of market crashes on the economy. Market downturns should usually be allowed to occur without interference, but we should understand the economic consequences of fiscal policy well enough to prevent disasters like the Great Depression and the most recent Great Recession. Normal business cycles are a healthy part of the economy because slight downturns create opportunities for the entrepreneur. There is great value in studying the actions of the entrepreneur because they help us to understand how information is processed to fuel exchange in the market. If there is any value at all in studying economic theory, it is in applying economic principles to markets in the real world.
  The most perfect computational models do no good if we do not understand the catallactics of exchange and cannot prevent catastrophic market failures. Economics should not be so much about equilibrium, but about catallactics @Buchanan1979. We need models that help us explain markets and prices as they actually are rather than as mathematics says they should be. By studying the exchanges that lead to the emergence of market prices, we can come to understand the flow of information and incentives that are that lead to exchange. This paper will discuss some popular assumptions of equilibrium economic models and why those assumptions severely limit the usefulness of their models. I will also explain why the Austrian market-process views are more useful to us than equilibrium models that view the economy as a state.


## Neo-Keynesian DSGE Models

  The Neo-Keynesian dynamic stochastic general equilibrium (DSGE) model has some fatal flaws that severely limit its usefulness in representing the real world. First, it assumes that people already possess all relevant information and that they behave predictably and rationally when in reality they do not @rickards2016road. It also claims that local equilibria can be aggregated into a complete whole without loss of important information. The third and most fatal flaw of the DSGE model is that it assumes the market prices to fall within a normal distribution. Normal distributions are not a good representation of prices because they ignore the possibility of extreme market events such as Black Monday and Black Thursday. According to a normally distributed model, such events should only occur every 40 million years, yet we have had several such events in the past 100 years @rickards2016road. Market prices are much more accurately represented by a Paretian distribution.
	
## General Availability of Information

  Economists often make the assumption that all information is readily available to everyone. They say that it is "given" in their models that everyone has access to all the information in the market. The fact is that such information is not always so easily found. One of the major flaws of popular economic models is that they offer no insight or explanation on how information is disseminated. According to Hayek, "To assume all the knowledge to be given to a single mind in the same manner in which we assume it to be given to us as the explaining economists is to assume the problem away and to disregard everything that is important and significant in the real world" @Hayek1945. He goes on to explain that each person has some unique knowledge that gives him an advantage over others in the market @Hayek1945. Economies function because each person leverages their particular knowledge and set of skills to find arbitrage opportunities. The economy is driven by the use of information by individuals whose circumstances are unique to the time and place @Hayek1945.
  
## Statistical Aggregates in Disequilibrium Markets
    If we aggregate all economic agents into one whole, then everything averages out into a nice model that tells us nothing about how exchanges are taking place. If economics is the study of market forces, then equilibrium economists are completely ignoring the process that they should be focusing on. Economic equilibrium models are useful to describe a state toward which the market tends to shift, but it is important to understand that markets are in a constant state of disequilibrium. If it were not so, then there would never be any change in behavior by any market participants. According to Stiglitz, "Equilibrium is a state where no economic agents have an incentive to change their behavior. . . the equality of demand and supply should not be taken as a definition of equilibrium, but rather as a consequence following from more primitive behavioral postulates" @stiglitz1987causes. Equilibrium would mean that all plans of each economic actor are in sync and can be executed compatibly. However, the economy actually consists of economic agents that have conflicting plans, and the ones with the best plans tend to edge out the others.
    As Thomsen explained, "the defining characteristic of equilibrium is not the equality of quantities supplied and demanded but, instead, the knowledge (and exploitation) by the trading agents of all profitable opportunities, that is, 'perfect' knowledge" @thomsen1992prices. Equilibrium, then, can only occur in an economy where each economic actor has a perfect knowledge of all arbitrage opportunities that are available and has already done everything he can to exploit them. Therefore, an equilibrium model of the economy completely ignores the exchange of information and does nothing to explain the knowledge problem. Many economists choose to ignore the study of disequilibrium because they assume that all disequilibrium situations will eventually become equilibrium situations and then they can explain them using their models @thomsen1992prices. However, they are missing what I believe to be the most important part of economics, which is explaining how the market process takes disequilibrium situations and pushes them toward equilibrium.

## The Optimization Problem

  One of the most widely accepted views of the economic agent is that he is a Robbinsian maximizer. Robbins defined the economic problem as an optimization problem in which the agent is choosing among alternatives with the objective of maximizing utility or profit @Buchanan1979. However, he makes some assumptions that the agent knows all the available options and has correct information about them. He claims that the economic problem is an allocation problem. I agree with the Austrian market-process school of thought that describes the economic problem as a knowledge problem. It is much more useful and realistic to explain how the movement of knowledge impacts prices and decision making than to simply assume that all knowledge is given and correct. To assume that everyone has a correct knowledge of all possible alternatives would mean that the economic problem would be reduced to a simple calculation of the utility maximization function. In reality, the world is full of possibilities for resource allocation and not everyone is aware of all the possible alternatives and their impact on utility.
    We should spend more effort attempting to explain what happens when utility is not being perfectly maximized by everyone, meaning that markets are not in equilibrium. T.W. Schultz once said that "determining precisely what people do who are not in equilibrium is not one of the notable achievements of economics' @schultz1975value, but perhaps it should be.
    
## The Role of Entrepreneurship

  One of the best ways to study this process of exchange in disequilibrium markets is to study the entrepreneur. An entrepreneur is someone who is able to discover and profit from previously unknown arbitrage opportunities @thomsen1992prices. That means they either find a new way to exploit an existing good or create and distribute a new product. As long as there is undiscovered information in markets, there will be arbitrage opportunities for people to learn about and exploit. It may not be possible to create a mathematical model that fully explains the behavior of the entrepreneur, but entrepreneurs perform a very important function in economies. They are the people who realize when resources are not being allocated in the best way possible and create a business to take advantage of that situation.
  
## Fiscal Policy and Rational Decision-Making

  At the root of equilibrium economic theory is the assumption that people are rational. People should choose rationally when presented with a situation, but they don't. Rational decision-making is the basis for modern fiscal policy. Rickards explained how this is supposed to work in the context of fiscal policy when he said, "When systemic equilibrium is perturbed through unemployment or recession, central bankers manipulate markets to emit price signals designed to induce preferred behaviors. Once the desired behavior results, equilibrium is restored, and growth is again optimized" @rickards2016road. That is how it is supposed to work. However, Rickards goes on to explain that people rarely behave in such a rational way, which means that "economic systems are not in equilibrium; they are complex, dynamic, and subject to critical state chaos and collapse" @rickards2016road. Rickards, Hayek, and Buchanan all agree that it is a mistake to sum up human behavior into statistical aggregates, because we lose a lot of information about the individual behaviors that drive the economy.
    In a recent experiment by Professor Ryan Whitby at Utah State University, students were asked to enter their student identification number, and then they were told to estimate what the price of an item should be. After repeating this experiment many times on different groups of students, he was able to show that students whose identification numbers start with a higher digit tended to price the item much higher than those whose identification number started with a low number. From this we can conclude that perception of market prices can be significantly affected by completely unrelated information. We can hypothesize from this that markets may not be able to achieve a set equilibrium for anything, since there will always be different perceptions about what prices should be.
    The only thing that economists can actually do to change markets is to manipulate the incentives in the marketplace by changing laws or fiscal policies. The Federal Reserve employs over 300 individuals with Ph.D.'s in economics, and yet they still cannot prevent major financial crises from occurring. If all we do is build complex mathematical models that do little to explain the real world, then economics as a social science provides little value. Some of the current methodologies in neoclassical economics are preventing economists from reaching their potential.
    
## The Problem with Modeling Market Prices Using a Normal Distribution

  Another erroneous belief of mainstream economists is that they assume the future will resemble the past. That is not necessarily the case; we cannot take the historical data of one price path from one timeline and extrapolate that out into the future saying that it is a normally distributed model. One of the greatest blunders economists make in their mathematical models is assuming that market prices are normally distributed. Bayesian statistics is more adept at modeling the real world than classical methods because it attempts to use current knowledge to predict the future without forcing the data to fit a normal distribution. 
  Market price movements can either be modeled by a traditional bell curve or by a power curve. The bell curve assumes that market prices are normally distributed and leaves no room for extreme events. It also assumes that the future reflects the past, but does not take into account current events to predict future changes, as Bayesian methodologies would suggest. A power curve is a much better tool to model market prices, and since it is not mean-reverting, it leaves room for extreme events. According to Rickards, "Empirical data reveal that market prices and extreme events are distributed along a power curve. The normal distribution is a fantasy" @rickards2016road. If the normal distribution is a fantasy, we should stop basing all our economic and financial models on it.
  
## Preventing Catastrophic Market Failures

  One of the most important jobs of economists is to predict when disastrous events will occur in markets, and to understand the incentives of the individual players in the market well enough to know what steps should be taken to avert such crises. According to Rickards, "Crises emerge because regulators don't comprehend the statistical properties of the systems they regulate" @rickards2016road. One of the roles of modern economics should be to use Bayesian decision making theories to model the behavior of individuals in disequilibrium situations.
  Bayesian decision-makers capture uncertainty by using a probability to represent an unknown future event. They assume that certain things make the event either more likely or less likely to occur, and when they learn new information, they use it to update their belief about the future @giocoli2013wald. Most people are Bayesian thinkers, but they don't actually make rational decisions like neoclassical economists claim they do. That means that we can use Bayesian statistical models to model macroeconomic trends, but not to model individual behavior.
  
# Summary and Conclusion

  The root of the economic problem is explaining the movement of knowledge and resources. Equilibrium models generally fail to do so because they simplify economic agents into statistical aggregates. Instead of showing a dynamic economy with many actors who have conflicting agendas, equilibrium models try to show how everything works in harmony to achieve a perfect economic balance of supply and demand where utility is maximized across the economy. They assume that everyone has perfect knowledge and correct information and is able to maximize their utility by allocating scarce resources in the best way possible. Such an idealistic state is a myth, and at best shows a state toward which the economy as a whole tends to drift. It is much more interesting to look at disequilibrium economies because we get insight into how people obtain and use information. Entrepreneurs are a good example of this. If the economy were in equilibrium, entrepreneurs would not exist. They see opportunities to profit from situations where others do not, so they become the engines that drive transformation in markets.
  We should not assume that people are rational decision-makers. Even with access to good information, people repeatedly make bad decisions. Modern fiscal policy is based on the assumption that people will react rationally to market signals from central bankers, but somehow they have not been able to stop catastrophic market failures from occurring. Based on their normally distributed statistical models, such events should almost never occur, but they occur quite frequently. Economists should consider using a power curve rather than a bell curve to model market prices. If we can understand the underlying dynamics of exchange in disequilibrium economies, then we should be able to develop better fiscal policies that promote a healthy economy. That will be the greatest economic achievement yet.




<!--
# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\vspace*{-0.2in}
\noindent
-->

